### ISSUE TITLE
How can i update the texture to display qimage dynamicly?

### ISSUE THREAD

**Issue by lanmanck** [tkarv/QOpenGLWindow_Examples#1]
Hi, tkarv:

there example are great, I am new to opengl, How can i update the texture to display qimage dynamically?
I need to display camera picture on the widget and minimize the cpu usage, opengl is a better method.
could you update an example dynamically changing the qimage?
thank you.

**Comment by tkarv** [comment]
Hey!

Dynamic texture from camera shouldn't be a big deal, since QOpenGLTexture IIRC can be constructed directly from QImage. You just need to update the texture when a new frame from the camera arrives. I probably have some code lying around somewhere, I'll see if I can set up an example based on that.

**Comment by lanmanck** [comment]
Hi, tkarv:
any updates? I try setData() api, it seems work but the picture's color is not the same as original, and when closing it an warning prompted

**Comment by tkarv** [comment]
Hey @lanmanck , sorry for taking so long to get back to you. I added an example of dynamically updating the texture based on video produced by QMediaPlayer and QVideoSink. Please check it out and let me know if there's any issues!

**Comment by lanmanck** [comment]
I read your code and now know how to update, thank you very much.
